/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_grephq_ot_Jusb */

#ifndef _Included_com_grephq_ot_Jusb
#define _Included_com_grephq_ot_Jusb
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_grephq_ot_Jusb
 * Method:    open
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_grephq_ot_Jusb_open
  (JNIEnv *, jclass);

/*
 * Class:     com_grephq_ot_Jusb
 * Method:    getDeviceAddress
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_grephq_ot_Jusb_getDeviceAddress
  (JNIEnv *, jclass);

/*
 * Class:     com_grephq_ot_Jusb
 * Method:    getDeviceList
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_grephq_ot_Jusb_getDeviceList
  (JNIEnv *, jclass);

/*
 * Class:     com_grephq_ot_Jusb
 * Method:    getDeviceSpeed
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_grephq_ot_Jusb_getDeviceSpeed
  (JNIEnv *, jclass);

/*
 * Class:     com_grephq_ot_Jusb
 * Method:    getPortNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_grephq_ot_Jusb_getPortNumber
  (JNIEnv *, jclass);

/*
 * Class:     com_grephq_ot_Jusb
 * Method:    getConfiguration
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_grephq_ot_Jusb_getConfiguration
  (JNIEnv *, jclass);

/*
 * Class:     com_grephq_ot_Jusb
 * Method:    getDescriptor
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_grephq_ot_Jusb_getDescriptor
  (JNIEnv *, jclass);

/*
 * Class:     com_grephq_ot_Jusb
 * Method:    getBusNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_grephq_ot_Jusb_getBusNumber
  (JNIEnv *, jclass);

/*
 * Class:     com_grephq_ot_Jusb
 * Method:    freeDeviceList
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_grephq_ot_Jusb_freeDeviceList
  (JNIEnv *, jclass);

/*
 * Class:     com_grephq_ot_Jusb
 * Method:    setConfiguration
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_grephq_ot_Jusb_setConfiguration
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_grephq_ot_Jusb
 * Method:    setDebug
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_grephq_ot_Jusb_setDebug
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_grephq_ot_Jusb
 * Method:    resetDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_grephq_ot_Jusb_resetDevice
  (JNIEnv *, jclass);

/*
 * Class:     com_grephq_ot_Jusb
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_grephq_ot_Jusb_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
